// packages/ir/src/index.ts
// public surface for the typed Scratch IR (import/export, canonicalize, summarize, ops)

export * from './core/json.js'
export * from './core/uid.js'
export * from './project/build.js'
export * from './project/scripts.js'
export * from './project/target-ir.js'
export * from './project/project-ir.js'
export * from './project/roundtrip.js'
export * from './project/summarize.js'
export * from './project/projects.js'
export * from './repair/edit-graph.js'
export * from './project/project-delta.js'
export * from './project/preservation.js'
export * from './project/target-properties.js'
export * from './repair/repair-types.js'
export * from './repair/repair-schema.js'
export * from './repair/repair-blocks.js'
export * from './repair/repair-ops.js'
export * from './edit/reference-index-types.js'
export * from './edit/reference-index.js'
export * from './edit/own-record.js'
export * from './edit/procedure-mutation.js'
export * from './edit/project-index-compatibility.js'
export * from './edit/lineage.js'
export * from './edit/correspondence.js'
export * from './edit/authorization.js'
