// packages/localize/src/structural/types.ts
// compatibility reexports for IR-owned semantic reference-index contracts

export {
  blockKey,
  commentKey,
  declarationKey,
  mediaKey,
  monitorKey,
  procedureKey,
  scriptKey,
  targetKey,
} from '@scratch-agent/ir'
export type {
  BroadcastResolutionStatus,
  BroadcastResolution,
  BroadcastResolutionSource,
  BroadcastUse,
  BroadcastUseSource,
  CommentAttachmentStatus,
  CommentRef,
  DeclarationAccess,
  DeclarationResolution,
  DeclarationResolutionSource,
  DeclarationResolutionStatus,
  DeclarationUse,
  DeclarationUseSource,
  IndexedBlock,
  IndexedBroadcast,
  IndexedComment,
  IndexedDeclaration,
  IndexedEventHat,
  IndexedMedia,
  IndexedMonitor,
  IndexedProcedure,
  IndexedProcedureParameter,
  IndexedScript,
  InputChildRef,
  InputChildSlot,
  LocalizationIndexes,
  MediaKind,
  DynamicMediaSelectorReason,
  DynamicMediaSelectorReference,
  MediaOrderReference,
  MediaOrderSelectorKind,
  MediaRef,
  MediaReference,
  MediaReferenceDomain,
  MediaResolutionStatus,
  MonitorRef,
  OwnershipStatus,
  ProcedureMutationIssue,
  ReferenceCardinality,
  SemanticInboundReference,
  SemanticInboundReferenceKind,
  SemanticReferenceIndex,
  SpriteReference,
  SpriteReferenceKind,
  SpriteReferenceSourceStatus,
  SpriteTargetResolutionStatus,
  UnresolvedBlockCommentReference,
} from '@scratch-agent/ir'
